[package]
name = "net"
version = "0.1.0"
edition = "2024"

[dependencies]
broker = { path = "../broker" }
protocol = { path = "../protocol" }
tokio = { version = "1.28.2", features = [
    "net",
    "io-util",
    "macros",
    "rt-multi-thread",
] }
bytes = "1.11.0"
