[package]
name = "client-bin"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = [
    "net",
    "io-util",
    "macros",
    "rt-multi-thread",
] }
bytes = "1.11.0"
protocol = { path = "../../crates/protocol" }
common = { path = "../../crates/common" }
